# Generated by Django 5.1.2 on 2024-12-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_studant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studant',
            new_name='Student',
        ),
    ]
